name: Build and Release

on:
  push:
    branches:
      - "master"

jobs:    
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: CompeyDev/rojo-build-action@0.1.5
        with:
          output: RoundHandler
          type: rbxm

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: vPre-${{ github.run_number }}
          release_name: Release vPre-${{ github.run_number }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload RoundHandler
        id: upload-roundhandler
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./RoundHandler.rbxm
          asset_name: RoundHandler.rbxm
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}