name: Build and Release

on:
  push:
    branches:
      - "changelog-nonsense"
    tags:
      - '*'

jobs:    
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          cache: true

      - name: Install Lune
        run: aftman install

      - name: Build project
        run: lune run build

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: vPre-${{ github.run_number }}
          release_name: Release vPre-${{ github.run_number }}
          draft: false
          prerelease: true
          body: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload RoundHandler
        id: upload-roundhandler
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./RoundHandler.rbxm
          asset_name: RoundHandler.rbxm
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}